FROM nvidia/opengl:1.2-glvnd-runtime-ubuntu20.04
# Setup environment
ENV LANG C.UTF-8
ENV LC_AL C.UTF-8
ENV ROS_DISTRO noetic
ENV TZ=Europe/Zagreb 
ENV NVIDIA_VISIBLE_DEVICES all
ENV NVIDIA_DRIVER_CAPABILITIES graphics,utility,compute 
# Setup timezone 
RUN ln -snf /usr/share/zoneinfo/${TZ} /etc/localtime && echo ${TZ} > /etc/timezone 
# Install dependencies
RUN apt-get update && apt-get install -y git \
    tmux \
    nano \
    python3-pip \
    libeigen3-dev \
    liburdfdom-dev \ 
    liboctomap-dev \
    libassimp-dev \
    libboost-all-dev \
    gnome-terminal \
    dbus-x11 \
    libcanberra-gtk-module \ 
    libcanberra-gtk3-module \
    && rm -rf /var/lib/apt/lists/*
    
RUN sh -c 'echo "deb http://packages.ros.org/ros/ubuntu focal main" > /etc/apt/sources.list.d/ros-latest.list'
RUN apt-key adv --keyserver 'hkp://keyserver.ubuntu.com:80' --recv-key C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654
RUN apt-get update
# Install ROS
RUN apt-get update && apt-get install -y \
    ros-${ROS_DISTRO}-ros-core \
    ros-${ROS_DISTRO}-robot-state-publisher \
    ros-${ROS_DISTRO}-joint-state-publisher \
    ros-${ROS_DISTRO}-xacro \
    ros-${ROS_DISTRO}-catkin \
    ros-${ROS_DISTRO}-control-toolbox \
    ros-${ROS_DISTRO}-controller-interface \
    ros-${ROS_DISTRO}-ros-control \ 
    ros-${ROS_DISTRO}-ros-controllers \
    ros-${ROS_DISTRO}-tf-conversions \
    ros-${ROS_DISTRO}-rqt-gui \
    ros-${ROS_DISTRO}-hardware-interface \
    ros-${ROS_DISTRO}-interactive-markers \
    ros-${ROS_DISTRO}-realtime-tools \
    ros-${ROS_DISTRO}-tf \
    ros-${ROS_DISTRO}-urdf \
    ros-${ROS_DISTRO}-robot-state-publisher \
    ros-${ROS_DISTRO}-controller-interface \
    ros-${ROS_DISTRO}-rviz \
    python3-catkin-pkg \
    python3-catkin-tools \
    python3-rosdep \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /home/developer
# lcm lib
RUN apt-get update && apt-get install -y build-essential libglib2.0-dev git cmake -y \
    && git clone https://github.com/lcm-proj/lcm.git \
    && cd lcm \
    && mkdir build && cd build  \
    && cmake .. \
    && make -j$(nproc) \
    && make install
# RUN ln -s /usr/lib/x86_64-linux-gnu/liblcm.so  /usr/local/lib/liblcm.so TODO: removed..
# drake
RUN apt-get update -y && apt-get install --no-install-recommends ca-certificates gnupg lsb-release wget -y \
    && wget -qO- https://drake-apt.csail.mit.edu/drake.asc | gpg --dearmor - | tee /etc/apt/trusted.gpg.d/drake.gpg >/dev/null \
    && echo "deb [arch=amd64] https://drake-apt.csail.mit.edu/$(lsb_release -cs) $(lsb_release -cs) main" | tee /etc/apt/sources.list.d/drake.list >/dev/null \
    && apt-get update -y \
    && apt-get install --no-install-recommends drake-dev=1.19.0-1 -y \
    && echo 'export PATH="/opt/drake/bin${PATH:+:${PATH}}"' >> /root/.zshrc \
    && echo "export PYTHONPATH=\"/opt/drake/lib/python\$(python3 -c 'import sys; print(\"{0}.{1}\".format(*sys.version_info))')/site-packages\${PYTHONPATH:+:\${PYTHONPATH}}\"" >> /root/.zshrc \
    && echo 'export PATH="/opt/drake/bin${PATH:+:${PATH}}"' >> /root/.bashrc \
    && echo "export PYTHONPATH=\"/opt/drake/lib/python\$(python3 -c 'import sys; print(\"{0}.{1}\".format(*sys.version_info))')/site-packages\${PYTHONPATH:+:\${PYTHONPATH}}\"" >> /root/.bashrc


# casadi
RUN apt-get update -y && apt-get install gcc g++ gfortran git cmake liblapack-dev pkg-config --install-recommends -y \
    && git clone https://github.com/casadi/casadi.git \
    && cd casadi \
    && git checkout 3.5.5 \
    && mkdir build && cd build \
    && cmake .. -DWITH_EXAMPLES=OFF \
    && make -j$(nproc) \
    && make install


# mujoco
RUN apt-get update -q \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y \
    curl \
    git \
    libgl1-mesa-dev \
    libgl1-mesa-glx \
    libglew-dev \
    libosmesa6-dev \
    software-properties-common \
    net-tools \
    vim \
    virtualenv \
    wget \
    xpra \
    xserver-xorg-dev \
    libglfw3-dev \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

ENV LANG C.UTF-8
# ENV MUJOCO_NET https://github.com/google-deepmind/mujoco/releases/download/2.1.0/mujoco210-linux-x86_64.tar.gz
RUN mkdir -p /root/.mujoco \
    && wget https://mujoco.org/download/mujoco210-linux-x86_64.tar.gz -O mujoco.tar.gz \
    && tar -xf mujoco.tar.gz -C /root/.mujoco \
    && rm mujoco.tar.gz \
    && echo 'export LD_LIBRARY_PATH=/root/.mujoco/mujoco210/bin' >> /root/.bashrc \
    && echo 'export PATH=$LD_LIBRARY_PATH:$PATH' >> /root/.bashrc \
    && echo 'export LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libGLEW.so' >> /root/.bashrc \
    && echo 'export LD_LIBRARY_PATH=/root/.mujoco/mujoco210/bin' >> /root/.zshrc \
    && echo 'export PATH=$LD_LIBRARY_PATH:$PATH' >> /root/.zshrc \
    && echo 'export LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libGLEW.so' >> /root/.zshrc

# mujoco-py
RUN apt-get update -y && apt-get install python3-pip git -y \
    && git clone https://github.com/openai/mujoco-py.git \
    && cd mujoco-py \
    && pip3 install -U 'mujoco-py<2.2,>=2.1' \
    && pip3 install -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple \
    && pip3 install -r requirements.dev.txt -i https://pypi.tuna.tsinghua.edu.cn/simple \
    && python3 setup.py install \
    && pip3 install mujoco \
    && pip3 install pynput

# Set the default shell to bash
SHELL ["/bin/bash", "-c"]
# Add user and add it to sudo group
#RUN adduser --disabled-password --gecos '' developer 
#RUN adduser developer sudo 
#RUN echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers
#RUN adduser developer dialout
#USER developer 
WORKDIR /home/developer
# Create new workspace for aerial manipulator
RUN mkdir -p catkin_ws/src
WORKDIR /home/developer/catkin_ws
RUN catkin init
WORKDIR /home/developer/catkin_ws/src
## Clone OCS2
#RUN git clone https://github.com/leggedrobotics/ocs2.git
# ocs2
RUN apt-get update -y && apt-get install git -y \
    && apt-get install liburdfdom-dev liboctomap-dev libassimp-dev ros-noetic-rqt-multiplot ros-noetic-grid-map-rviz-plugin -y \
    # Clone pinocchio and hpp-fcl
    && git clone --recurse-submodules https://github.com/leggedrobotics/hpp-fcl.git \
    && cd hpp-fcl \
    && mkdir build && cd build \
    && cmake .. \
    && make -j$(nproc) \
    && make install \
    && git clone --recurse-submodules https://github.com/leggedrobotics/pinocchio.git \
    && cd pinocchio \
    && mkdir build && cd build \
    && cmake .. \
    && make -j$(nproc) \
    && make install
## Clone ocs2_robotic_assets
# RUN git clone https://github.com/leggedrobotics/ocs2_robotic_assets.git
RUN catkin config -DCMAKE_BUILD_TYPE=RelWithDebInfo
#RUN catkin build ocs2_legged_robot_ros ocs2_self_collision_visualization
#RUN source /opt/ros/noetic/setup.bash
RUN echo "source /opt/ros/noetic/setup.bash" >> ~/.bashrc
RUN echo "source /home/developer/catkin_ws/devel/setup.bash" >> ~/.bashrc
#RUN pip3 install mujoco
#RUN pip3 install pynput
##### kuavo
RUN apt-get update -y && apt-get install libeigen3-dev libboost-all-dev -y \
    && apt-get install libyaml-cpp-dev libtinyxml2-dev -y \
    && apt-get install libncurses5-dev libncursesw5-dev -y \
    && apt-get install libmodbus-dev -y \
    && apt-get install liblcm-dev libgflags-dev libgoogle-glog-dev liblmdb-dev -y \
    && apt-get install libgflags-dev libgoogle-glog-dev liblmdb-dev -y \
    # set robot version
    && echo 'export ROBOT_VERSION=34' >> /root/.bashrc \
    && echo 'export ROBOT_VERSION=34' >> /root/.zshrc

    
# Copy kuavo_mpc files
COPY . /home/developer/catkin_ws/src/kuavo-ros-control
RUN bash -c "source /opt/ros/noetic/setup.bash; catkin build -j 2 humanoid_controllers humanoid_interface_ros mujoco_sim biped_s3"